2A

In [0]:
def evaluateTaylor(x):

  y = (x - 1) - 1/2 * (x - 1) + 1/3 * (x - 1)**3
  
  return y

2B

In [0]:
from numpy import *

v1 = array([3, 7, 1])
v2 = zeros(6)
v3 = ones(3)
v4 = arange(1, 5)
v5 = concatenate((arange(1, 5), arange(10, 14)))

print(v1[0])
print(v4[1])
# print(v3[3]) index out of bounds
v4 = append(v4, [10])
print(v4)
v5 = array([3, 7, 1])
print(v5)

2C

In [0]:
def script(v1, v2, v3):

  print(dot(v1, v2))
  print(multiply(v1, v2))
  print(sin(v1))
  print(size(v1))
  # print(dot(v1, v3)) v1 is longer than v3

In [0]:
v1 = arange(1, 6)
v2 = arange(3, 8)
v3 = ones(4)

script(v1, v2, v3)

85
[ 3  8 15 24 35]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
5


2D

In [0]:
v1 = array([4, 2, 1, 2, 5])
v2 = array([-1, 4, 5, -3, 6])

v3 = v1[v1 < 3]
v3 = v2[v2 < 0]
v3 = v2[v2 > 0]
v3 = v1[v1 > 100]
v3 = v1[v1 > v2]
v3 = v2[v2 != 5]
v3 = v1[v1 > mean(v1)]

2E

In [0]:
v = array([4, 7, -2, 9, 3 -6, -4, 1])

v[v < 0] = 0
v = -v
v[v < mean(v)] = 0
v[v < 0] = abs(v)
v[v > 0] = v[v > 0] * 2
v = v ** 2

2F

In [0]:
def computeProjection(a):

  b = np.ones(np.size(a))

  projection = np.dot(a, b) / np.linalg.norm(a)**2 * a

  return projection

array([ 0.4, -0.2])

2G

In [0]:
def boxArea(boxCorners, area):

  if area == 'Box1':
    A = (boxCorners[1] - boxCorners[0]) * (boxCorners[5] - boxCorners[4])
  elif area == 'Box2':
    A = (boxCorners[3] - boxCorners[2]) * (boxCorners[7] - boxCorners[6])
  elif area == 'Intersection':
    A = np.dot(
    max(0, min(boxCorners[1], boxCorners[3]) - max(boxCorners[0], boxCorners[2])),
    max(0, min(boxCorners[5], boxCorners[7]) - max(boxCorners[4], boxCorners[6]))
    )
  elif area == 'Union':
    A1 = (boxCorners[1] - boxCorners[0]) * (boxCorners[5] - boxCorners[4])
    A2 = (boxCorners[3] - boxCorners[2]) * (boxCorners[7] - boxCorners[6])
    AI = np.dot(
    max(0, min(boxCorners[1], boxCorners[3]) - max(boxCorners[0], boxCorners[2])),
    max(0, min(boxCorners[5], boxCorners[7]) - max(boxCorners[4], boxCorners[6]))
    )
    A = A1 + A2 - AI
  return A

import numpy as np
print(boxArea(np.array([5,20,14,25,12,23,5,17]), "Intersection"))

30


2H

In [4]:
def fillSudokuRow(sudokuRow):

  sudokuRow[sudokuRow == 0] = np.sum(np.arange(1, 10)) - np.sum(sudokuRow)

  return sudokuRow

import numpy as np
print(fillSudokuRow(np.array([9, 4, 0, 1, 5, 7, 2, 3, 8])))

[9 4 6 1 5 7 2 3 8]
